### ISSUE TITLE
Wrong conclusion about yield performance in Chapter 6

### ISSUE THREAD

**Issue by huanlin** [PacktPublishing/High-Performance-Programming-in-CSharp-and-.NET#2]
There is a problem in Chapter 6, section title "Exploring the yield keyword." 
The author compared performance with the following code:
https://github.com/PacktPublishing/High-Performance-Programming-in-CSharp-and-.NET/blob/bfcc807d81ff7826ceafe5e4481a0b809e03e602/CH06/CH06_Collections/CH06_Collections/Yield.cs#L57-L81

In the book, there is a picture of the benchmark result showing GetValuesYield is 903,628.26 times faster than GetValues method, then the author tells readers:

> "So, you can see that the use of the yield keyword is very beneficial to the performance of your computer programs." 

Then he closed this section without any further explanation. 
Wait! That's not the end of the story. The author's conclusion is misleading because he is comparing different things.
In the GetValuesYieldBenchmark method, it shoud force the whole process of yield be executed, for example converting IEnumerable to List:

```C#
[Benchmark]
public void GetValuesYieldBenchmark()
{
    var data = GetValuesYield().ToList();            
}
```
Then it can be compared with GetValuesBenchmark method.
The author claimed yield is 903,628.26 times faster than List<T> is misleading.

**Comment by jasonalls** [comment]
You are indeed correct. That was an oversight on my behalf. I have updated the code accordingly. Both methods now return an IEnumerable<object[]>, with one using the yield keyword, and the other not.

The new benchmarks are as follows:

![image](https://user-images.githubusercontent.com/11942797/195680356-f3ee6b59-bd5c-4a07-a491-0953ae0fbb36.png)

This graphic shows that using the yield keyword to return a collection of values is faster than returning the same collection without using the yield keyword. In this example, using the yield keyword increases performance by an order of 14.31 times.

The GetValues method uses eager loading to build up the full collection before returning it. Whereas the GetValuesYield method uses lazy loading which returns one value at a time.

**Comment by huanlin** [comment]
Thank you for clarifying this.
